# Generated by Django 2.2.4 on 2019-08-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'inscrição', 'verbose_name_plural': 'inscrições'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
